version: "3"

services:
  node:
    env_file:
      - .env
    image: berachain-node-debug:0.0.0
    user: ":"
    volumes:
      - ./local:/.berad
    command:
      - start
    ports:
      - "26653:26653"
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
  oracle-feeder:
      depends_on:
        - node
      env_file:
        - .env
      image: berachain-node-debug:0.0.0
      user: ":"
      environment:
        - PRICE_FEEDER_PASS=${PRICE_FEEDER_PASS}
      volumes:
        - ./local:/.berad
      command: ["oracle-feeder", "/.berad/oracle/config.toml"]
      ports:
        - "7171:7171"
networks:
  default:
    name: berachain-network