version: "3"

services:
  berad:
    image: ghcr.io/berachain/berachain-node:latest
    user: $UID:$GID
    volumes:
      - ./config:/berachain/.berad/config
      - ./data:/berachain/.berad/data
    command:
      - start
    ports:
      - "26657:26657"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"